baseURL: "https://mapuekyle.com"
languageCode: en-us
title: Kyle Mapue
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    # - identifier: projects
    #   name: Projects
    #   url: /projects
    #   weight: 30
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    # - identifier: search
    #   name: Search
    #   url: /search
    #   weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  label:
    text: "Kyle Mapue"
    icon: "images/coding.png"
    iconHeight: 35
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon.ico"

  # for enchanced SEO
  env: production

  

  # Home Page
  profileMode:
    enabled: true
    title: "Welcome! \U0001F44B"
    subtitle: Hi 👋! I'm **Kyle Mapue**, an ambitious DevOps at [**Globe Telecom**](https://globe.com.ph), a national Telecom giant. I love the intricacies of how structures work and that's why I am fascinated with Cloud Computing and DevOps practices!
    # buttons:
    #   - name: CVterminal
    #     url: "https://cv-terminal-kyle.netlify.app"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "kyle.mapue@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/kyle-mapue-a06938212/"
    - name: "github"
      url: "https://github.com/kylemaps"
    - name: "cv"
      url: "https://drive.google.com/file/d/1upHaeuLTg-v_wN0AuDwKAyvBmehmQYze/view?usp=sharing"
    - name: "project"
      url: "https://cv-terminal-kyle.netlify.app"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
